
const cityData = [
    {'city': 'Zurich', 'country': 'Switzerland', 'country_code': 'CH', 'created_at':null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 43.6, 
                            'Apps that direct you to an available parking space have reduced': 44.5, 
                            'Bicycle hiring has reduced congestion': 55.6, 
                            'Online scheduling and ticket sales has made public transport easy': 79.7, 
                            'The city provides information on traffic congestion through mobile apps': 61.8}, 
     'traffic_congestion_not_a_problem': 41.0, 'public_transport_satisfactory': 80.0, 'smart_city_ranking': 'AAA'},

    {'city': 'Singapore', 'country': 'Singapore', 'country_code': 'SG', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 57.6, 
                            'Apps that direct you to an available parking space have reduced': 57.5, 
                            'Bicycle hiring has reduced congestion': 56.7, 
                            'Online scheduling and ticket sales has made public transport easy': 63.2, 
                            'The city provides information on traffic congestion through mobile apps': 75.7}, 
     'traffic_congestion_not_a_problem': 50.0, 'public_transport_satisfactory': 78.5, 'smart_city_ranking': 'A'},

    {'city': 'Mexico City', 'country': 'Mexico', 'country_code': 'MX', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 42.6, 
                            'Apps that direct you to an available parking space have reduced': 43.0, 
                            'Bicycle hiring has reduced congestion': 52.8, 
                            'Online scheduling and ticket sales has made public transport easy': 55.1, 
                            'The city provides information on traffic congestion through mobile apps': 63.4}, 
     'traffic_congestion_not_a_problem': 23.4, 'public_transport_satisfactory': 33.0, 'smart_city_ranking': 'C'},

    {'city': 'Rome', 'country': 'Italy', 'country_code': 'IT', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 32.4, 
                            'Apps that direct you to an available parking space have reduced': 35.0, 
                            'Bicycle hiring has reduced congestion': 35.1, 
                            'Online scheduling and ticket sales has made public transport easy': 57.1, 
                            'The city provides information on traffic congestion through mobile apps': 44.5}, 
     'traffic_congestion_not_a_problem': 11.8, 'public_transport_satisfactory': 17.7, 'smart_city_ranking': 'CCC'},

    {'city': 'Bogota', 'country': 'Colombia', 'country_code': 'CO', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 36.4, 
                            'Apps that direct you to an available parking space have reduced': 39.4, 
                            'Bicycle hiring has reduced congestion': 46.5, 
                            'Online scheduling and ticket sales has made public transport easy': 48.8, 
                            'The city provides information on traffic congestion through mobile apps': 58.7}, 
     'traffic_congestion_not_a_problem': 16.1, 'public_transport_satisfactory': 22.9, 'smart_city_ranking': 'D'},

    {'city': 'Cairo', 'country': 'Egypt', 'country_code': 'EG', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 58.9, 
                            'Apps that direct you to an available parking space have reduced': 61.0, 
                            'Bicycle hiring has reduced congestion': 50.8, 
                            'Online scheduling and ticket sales has made public transport easy': 65.2, 
                            'The city provides information on traffic congestion through mobile apps': 63.4}, 
     'traffic_congestion_not_a_problem': 20.6, 'public_transport_satisfactory': 49.4, 'smart_city_ranking': 'C'},

    {'city': 'Delhi', 'country': 'India', 'country_code': 'IN', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 64.9, 
                            'Apps that direct you to an available parking space have reduced': 65.5, 
                            'Bicycle hiring has reduced congestion': 69.0, 
                            'Online scheduling and ticket sales has made public transport easy': 78.2, 
                            'The city provides information on traffic congestion through mobile apps': 71.7}, 
     'traffic_congestion_not_a_problem': 25.3, 'public_transport_satisfactory': 67.5, 'smart_city_ranking': 'CC'},

    {'city': 'Osaka', 'country': 'Japan', 'country_code': 'JP', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 27.1, 
                            'Apps that direct you to an available parking space have reduced': 34.4, 
                            'Bicycle hiring has reduced congestion': 28.1, 
                            'Online scheduling and ticket sales has made public transport easy': 46.7, 
                            'The city provides information on traffic congestion through mobile apps': 54.2}, 
     'traffic_congestion_not_a_problem': 38.0, 'public_transport_satisfactory': 73.3, 'smart_city_ranking': 'B'},

    {'city': 'Toronto', 'country': 'Canada', 'country_code': 'CA', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 38.5, 
                            'Apps that direct you to an available parking space have reduced': 42.6, 
                            'Bicycle hiring has reduced congestion': 42.1, 
                            'Online scheduling and ticket sales has made public transport easy': 55.3, 
                            'The city provides information on traffic congestion through mobile apps': 53.9}, 
     'traffic_congestion_not_a_problem': 14.2, 'public_transport_satisfactory': 46.8, 'smart_city_ranking': 'BBB'},
     {'city': 'Melbourne', 'country': 'Australia', 'country_code': 'AU', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 38.4, 
                            'Apps that direct you to an available parking space have reduced': 39.5, 
                            'Bicycle hiring has reduced congestion': 40.9, 
                            'Online scheduling and ticket sales has made public transport easy': 59.4, 
                            'The city provides information on traffic congestion through mobile apps': 54.7}, 
     'traffic_congestion_not_a_problem': 21.4, 'public_transport_satisfactory': 54.1, 'smart_city_ranking': 'A'},

    {'city': 'Gothenburg', 'country': 'Sweden', 'country_code': 'SE', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 32.0, 
                            'Apps that direct you to an available parking space have reduced': 42.3, 
                            'Bicycle hiring has reduced congestion': 46.2, 
                            'Online scheduling and ticket sales has made public transport easy': 71.1, 
                            'The city provides information on traffic congestion through mobile apps': 55.2}, 
     'traffic_congestion_not_a_problem': 30.5, 'public_transport_satisfactory': 50.9, 'smart_city_ranking': 'A'},

    {'city': 'Hong Kong', 'country': 'Hong Kong', 'country_code': 'HK', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 46.2, 
                            'Apps that direct you to an available parking space have reduced': 53.7, 
                            'Bicycle hiring has reduced congestion': 43.1, 
                            'Online scheduling and ticket sales has made public transport easy': 63.7, 
                            'The city provides information on traffic congestion through mobile apps': 69.2}, 
     'traffic_congestion_not_a_problem': 30.3, 'public_transport_satisfactory': 63.6, 'smart_city_ranking': 'A'},

    {'city': 'Riyadh', 'country': 'Saudi Arabia', 'country_code': 'SA', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 63.0, 
                            'Apps that direct you to an available parking space have reduced': 66.9, 
                            'Bicycle hiring has reduced congestion': 54.5, 
                            'Online scheduling and ticket sales has made public transport easy': 73.5, 
                            'The city provides information on traffic congestion through mobile apps': 70.9}, 
     'traffic_congestion_not_a_problem': 24.1, 'public_transport_satisfactory': 61.1, 'smart_city_ranking': 'B'},

    {'city': 'Seoul', 'country': 'South Korea', 'country_code': 'KR', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 43.4, 
                            'Apps that direct you to an available parking space have reduced': 50.1, 
                            'Bicycle hiring has reduced congestion': 46.1, 
                            'Online scheduling and ticket sales has made public transport easy': 72.8, 
                            'The city provides information on traffic congestion through mobile apps': 81.0}, 
     'traffic_congestion_not_a_problem': 20.5, 'public_transport_satisfactory': 72.7, 'smart_city_ranking': 'AA'},

    {'city': 'Oslo', 'country': 'Norway', 'country_code': 'NO', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 41.9, 
                            'Apps that direct you to an available parking space have reduced': 39.6, 
                            'Bicycle hiring has reduced congestion': 52.2, 
                            'Online scheduling and ticket sales has made public transport easy': 78.0, 
                            'The city provides information on traffic congestion through mobile apps': 46.9}, 
     'traffic_congestion_not_a_problem': 45.3, 'public_transport_satisfactory': 62.8, 'smart_city_ranking': 'AA'},

    {'city': 'Helsinki', 'country': 'Finland', 'country_code': 'FI', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 36.1, 
                            'Apps that direct you to an available parking space have reduced': 43.2, 
                            'Bicycle hiring has reduced congestion': 53.0, 
                            'Online scheduling and ticket sales has made public transport easy': 73.3, 
                            'The city provides information on traffic congestion through mobile apps': 45.3}, 
     'traffic_congestion_not_a_problem': 42.2, 'public_transport_satisfactory': 74.8, 'smart_city_ranking': 'AA'},

    {'city': 'Taipei City', 'country': 'Taiwan', 'country_code': 'TW', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 55.5, 
                            'Apps that direct you to an available parking space have reduced': 59.5, 
                            'Bicycle hiring has reduced congestion': 60.8, 
                            'Online scheduling and ticket sales has made public transport easy': 75.6, 
                            'The city provides information on traffic congestion through mobile apps': 75.0}, 
     'traffic_congestion_not_a_problem': 22.7, 'public_transport_satisfactory': 58.9, 'smart_city_ranking': 'BBB'},

    {'city': 'Ljubljana', 'country': 'Slovenia', 'country_code': 'SI', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 43.7, 
                            'Apps that direct you to an available parking space have reduced': 49.0, 
                            'Bicycle hiring has reduced congestion': 67.2, 
                            'Online scheduling and ticket sales has made public transport easy': 63.1, 
                            'The city provides information on traffic congestion through mobile apps': 47.3}, 
     'traffic_congestion_not_a_problem': 21.0, 'public_transport_satisfactory': 53.2, 'smart_city_ranking': 'BBB'},

    {'city': 'Luxembourg', 'country': 'Luxembourg', 'country_code': 'LU', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 35.8, 
                            'Apps that direct you to an available parking space have reduced': 37.7, 
                            'Bicycle hiring has reduced congestion': 47.0, 
                            'Online scheduling and ticket sales has made public transport easy': 57.4, 
                            'The city provides information on traffic congestion through mobile apps': 54.2}, 
     'traffic_congestion_not_a_problem': 26.1, 'public_transport_satisfactory': 73.0, 'smart_city_ranking': 'BBB'},

    {'city': 'Riga', 'country': 'Latvia', 'country_code': 'LV', 'created_at': null, 
     'mobility_solutions': {'Car-sharing Apps have reduced congestion': 43.8, 
                            'Apps that direct you to an available parking space have reduced': 48.0, 
                            'Bicycle hiring has reduced congestion': 45.7, 
                            'Online scheduling and ticket sales has made public transport easy': 64.8, 
                            'The city provides information on traffic congestion through mobile apps': 50.5}, 
     'traffic_congestion_not_a_problem': 31.8, 'public_transport_satisfactory': 59.9, 'smart_city_ranking': 'BB'}

];
